import React from "react";

const MucleMap = () => {
	return (
		<div id="muscle-map">
			<img
				id="background"
				src="https://musclewiki.com/static/Crops/00.-Blank-Figures.png"
			/>
			<img
				id="traps-a"
				src="https://musclewiki.com/static/Crops/08.-TrapsLeft.png"
			/>
			<img
				id="traps-b"
				src="https://musclewiki.com/static/Crops/08.-TrapsRight.png"
			/>
			<img
				id="shoulders-a"
				src="https://musclewiki.com/static/Crops/07.A-Deltoids.png"
			/>
			<img
				id="shoulders-b"
				src="https://musclewiki.com/static/Crops/07.B-Deltoids.png"
			/>
			<img
				id="pecs"
				src="https://musclewiki.com/static/Crops/06.-Pecs.png"
			/>
			<img
				id="biceps-a"
				src="https://musclewiki.com/static/Crops/05.A-Biceps.png"
			/>
			<img
				id="biceps-b"
				src="https://musclewiki.com/static/Crops/05.B-Biceps.png"
			/>
			<img
				id="forearm-a"
				src="https://musclewiki.com/static/Crops/14.A-Forearms.png"
			/>
			<img
				id="forearm-b"
				src="https://musclewiki.com/static/Crops/14.B-Forearms.png"
			/>
			<img
				id="obliques"
				src="https://musclewiki.com/static/Crops/04.-Obliques.png"
			/>
			<img
				id="quads-a"
				src="https://musclewiki.com/static/Crops/01.A-Quads.png"
			/>
			<img
				id="quads-b"
				src="https://musclewiki.com/static/Crops/01.B-Quads.png"
			/>
			<img
				id="calves-a"
				src="https://musclewiki.com/static/Crops/13.A-Calves.png"
			/>
			<img
				id="calves-b"
				src="https://musclewiki.com/static/Crops/13.B-Calves.png"
			/>
			<img
				id="back-traps-a"
				src="https://musclewiki.com/static/Crops/08.B-Traps.png"
			/>
			<img
				id="back-traps-b"
				src="https://musclewiki.com/static/Crops/08.C-Traps.png"
			/>
			<img
				id="back-shoulders-a"
				src="https://musclewiki.com/static/Crops/07.C-Deltoids.png"
			/>
			<img
				id="back-shoulders-b"
				src="https://musclewiki.com/static/Crops/07.D-Deltoids.png"
			/>
			<img
				id="triceps-a"
				src="https://musclewiki.com/static/Crops/09.A-Triceps.png"
			/>
			<img
				id="triceps-b"
				src="https://musclewiki.com/static/Crops/09.B-Triceps.png"
			/>
			<img
				id="back-lats-a"
				src="https://musclewiki.com/static/Crops/10.A-Lats.png"
			/>
			<img
				id="back-lats-b"
				src="https://musclewiki.com/static/Crops/10.B-Lats.png"
			/>
			<img
				id="back-lower"
				src="https://musclewiki.com/static/Crops/15.-Lower-Back.png"
			/>
			<img
				id="back-forearms-a"
				src="https://musclewiki.com/static/Crops/14.C-Forearms.png"
			/>
			<img
				id="back-forearms-b"
				src="https://musclewiki.com/static/Crops/14.D-Forearms.png"
			/>
			<img
				id="back-glutes"
				src="https://musclewiki.com/static/Crops/11.-Glutes.png"
			/>
			<img
				id="back-hamstrings-a"
				src="https://musclewiki.com/static/Crops/12.A-Hamstrings.png"
			/>
			<img
				id="back-hamstrings-b"
				src="https://musclewiki.com/static/Crops/12.B-Hamstrings.png"
			/>
			<img
				id="back-calves-a"
				src="https://musclewiki.com/static/Crops/13.C-Calves.png"
			/>
			<img
				id="back-calves-b"
				src="https://musclewiki.com/static/Crops/13.D-Calves.png"
			/>
		</div>
	);
};

export default MucleMap;
